import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import {mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const {chromium}=createRequire(import.meta.url)('playwright');
const fixture=(mode,s)=>JSON.parse(execFileSync('php',['tests/nettleser/henting-fixture.php',mode,JSON.stringify(s||{})],{encoding:'utf8'}));
const s=fixture('seed');const browser=await chromium.launch({args:['--host-resolver-rules=MAP lokal.lissom.no 127.0.0.1']});
const root=process.env.LISSOM_TEST_RAPPORT||(process.platform==='win32'?'C:/Users/info/kepler-lissom-analyse-20261001':join(tmpdir(),'lissom-nyadmin-kontroll'));mkdirSync(root,{recursive:true});
try{
 for(const width of [390,1280]){
  const c=await browser.newContext({viewport:{width,height:950}});await c.addCookies([{name:'lissom_sesjon',value:s.token,domain:'lokal.lissom.no',path:'/'}]);const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
  for(const [r,name]of [['idag','God oversikt. God arbeidsdag.'],['kalender','Kalender'],['kurs','Kurs'],['folk','Folk'],['penger','Penger'],['henting','Klar til henting'],['dugnad','Dugnad'],['ressurser','Ressurser og dreieskiver'],['foresporsler','Henvendelser'],['butikk','Butikk'],['brukere','Brukere'],['beskjeder','Beskjeder'],['verksted','Verksted'],['innhold','Innhold og synlighet'],['alle','Alle funksjoner'],['brenninger','Brenninger'],['vakter','Vakter'],['venteliste','Venteliste'],['arskalender','Årskalender'],['kursholdere','Kursholdere'],['oppskrifter','Oppskrifter'],['artikler','Nyttig info'],['referanser','Referanser'],['feilmeldinger','Feilmeldinger'],['tekster','Tekster på nettsiden'],['synlighet','Synlighet'],['seo','SEO'],['geo','GEO'],['ferie','Ferie og stengte dager'],['planer','Medlemskap'],['registrering','Registrer medlem'],['pameldte','Påmeldte og deltakere'],['soknader','Medlemssøknader'],['godkjenning','Til godkjenning'],['regnskap','Regnskap og dagsoppgjør'],['maler','Maler'],['varsler','Varsler og utsending'],['kursvelger','Kursvelger'],['kasse','Kasse'],['handlelister','Handlelister'],['internbutikk','Internbutikk'],['marked','Markedsføring'],['kampanjer','Kampanjer'],['kunnskap','Artikler og guider'],['innboks','Innboks · SoMe'],['frys','Frys av medlemskap'],['gaver','Medlemsgaver'],['rabatter','Grupperabatter'],['verktoy','Vedlikehold og verktøy'],['videokurs','Videokurs'],['betalinger','Betalinger'],['mobilvisning','Mobilvisning'],['timeliste','Timeliste'],['verving','Vervepremie'],['medlemsbidrag','Medlemsbidrag og galleri'],['maaling','Kjøpsmåling'],['aibilder','AI-bilder og oppsett'],['dokumenter','Dokumenter og håndbøker'],['dubletter','Dubletter i medlemslisten'],['bilder','Bildebibliotek'],['lenker','Nyttige lenker'],['kursstandard','Standardtekster for kurs'],['vippsoppsett','Vipps og betalingsvarsler']]){
   await p.goto(`http://lokal.lissom.no:8140/admin-ny.html#${r}`);await p.getByRole('heading',{name,exact:true}).waitFor();assert.equal(await p.locator('iframe').count(),r==='mobilvisning'?1:0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${width} ${r}: ingen horisontal rulling`);console.log(`${width} px · ${r}: eget skjermbilde kontrollert`);
   if(r==='alle'){const links=await p.locator('.directory a').evaluateAll(rows=>rows.map(a=>a.getAttribute('href')));assert.ok(links.length>=51);assert.deepEqual(links.filter(h=>!h.startsWith('#')),['/skisser.html']);}assert.equal(await p.locator('#mobil a.mobile-link').count(),5);assert.equal(await p.locator('#mobil').evaluate(n=>[...n.childNodes].some(c=>c.nodeType===3&&c.textContent.trim())),false);if(['idag','kalender','folk'].includes(r))await p.screenshot({path:`${root}/arbeidsrom-${r}-${width}.png`,fullPage:true});
  }
  await p.goto('http://lokal.lissom.no:8140/admin-ny.html#handlelister');if(await p.getByRole('button',{name:'Fraktpriser',exact:true}).count()){await p.getByRole('button',{name:'Fraktpriser',exact:true}).click();await p.getByRole('spinbutton',{name:'Energitillegg i prosent',exact:true}).waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.locator('dialog .close').click();}await p.goto('http://lokal.lissom.no:8140/admin-ny.html#kurs');await p.getByRole('searchbox',{name:'Søk etter kurs'}).fill(s.tag);await p.getByRole('button',{name:'Kursinnstillinger',exact:true}).click();await p.getByRole('button',{name:'Booking og kursholder',exact:true}).click();await p.getByRole('combobox',{name:'Delt ressurs',exact:true}).waitFor();await p.locator('dialog').last().locator('.close').click();await p.getByRole('button',{name:'Kursinnhold',exact:true}).click();await p.getByRole('textbox',{name:'Søkebeskrivelse',exact:true}).waitFor();await p.locator('dialog').last().locator('.close').click();await p.locator('dialog .close').click();console.log('Fraktpriser og kursinnstillinger åpner uten feil.');
  await p.goto(`http://lokal.lissom.no:8140/admin-ny.html#pameldte?booking=${s.booking}`);await p.getByRole('button',{name:'Endre antall plasser',exact:true}).waitFor();assert.equal(await p.locator('dialog').count(),1);await p.locator('dialog .close').click();console.log('Direktelenke åpner riktig påmelding i egen deltakerdialog.');
  await p.reload();await p.getByRole('button',{name:'Betalingshistorikk',exact:true}).click();await p.getByRole('button',{name:'Registrer mottatt betaling',exact:true}).waitFor();assert.match(await p.locator('dialog').last().innerText(),/Merket betalt/);await p.locator('dialog').last().locator('.close').click();await p.locator('dialog .close').click();

  await p.getByRole('searchbox',{name:'Søk etter personer og funksjoner'}).fill('klar henting');await p.locator('.search-results').getByRole('link',{name:/Klar til henting/}).click();await p.getByRole('heading',{name:'Klar til henting',exact:true}).waitFor();
  await p.getByRole('searchbox',{name:'Søk kurs som er klare til henting'}).fill(s.tag);await p.getByRole('button',{name:'Åpne og publiser',exact:true}).click();await p.getByRole('button',{name:'Publiser på ferdigbrent',exact:true}).waitFor();assert.match(await p.locator('dialog').innerText(),/1 mangler e-post/);let posts=0;p.on('request',r=>{if(r.method()==='POST')posts++;});await p.getByRole('button',{name:'Publiser på ferdigbrent',exact:true}).click();await p.getByRole('button',{name:'Avbryt',exact:true}).click();assert.equal(posts,0,'Avbryt publisering skriver ikke');await p.locator('dialog .close').click();
  await p.goto('http://lokal.lissom.no:8140/admin-ny.html#kurs');await p.getByRole('searchbox',{name:'Søk etter kurs'}).fill(s.tag);await p.getByRole('button',{name:'Rediger',exact:true}).click();await p.getByRole('textbox',{name:'Kursnavn'}).fill(s.tag+' endret');await p.getByRole('button',{name:'Avbryt',exact:true}).click();await p.getByRole('button',{name:'Forkast',exact:true}).click();assert.equal(await p.locator('dialog').count(),0);assert.equal(posts,0,'Forkast skriver ikke');
  await p.getByRole('button',{name:'Rediger',exact:true}).click();await p.getByRole('textbox',{name:'Kursnavn'}).fill(s.tag+' ulagret');await p.evaluate(()=>location.hash='folk');await p.getByRole('dialog',{name:'Forkaste endringene?',exact:true}).getByRole('button',{name:'Avbryt',exact:true}).click();assert.match(p.url(),/#kurs$/);await p.evaluate(()=>location.hash='folk');await p.getByRole('button',{name:'Forkast',exact:true}).click();await p.getByRole('heading',{name:'Folk',exact:true}).waitFor();await p.getByRole('searchbox',{name:'Søk navn, e-post eller telefon'}).fill(s.tag);await p.getByRole('button',{name:'Se person',exact:true}).click();await p.getByRole('heading',{name:'Betalingshistorikk',exact:true}).waitFor();await p.locator('dialog .close').click();console.log('Ulagret tekst beskyttes ved navigasjon; egen personvisning åpner.');
  await p.goto('http://lokal.lissom.no:8140/admin-ny.html#kurs');await p.getByRole('searchbox',{name:'Søk etter kurs'}).fill(s.tag);
  if(width===1280){
   await p.getByRole('button',{name:'Rediger',exact:true}).click();await p.getByRole('spinbutton',{name:'Antall plasser'}).fill('9');await p.getByRole('combobox',{name:'Synlighet'}).selectOption('kladd');await p.getByRole('checkbox',{name:'SMS-påminnelse'}).check();await p.getByRole('button',{name:'Lagre',exact:true}).click();await p.locator('dialog').waitFor({state:'detached'});const d=await p.evaluate(async()=>await(await fetch('/api/admin/kurs.php')).json());const k=d.kurs.find(k=>k.tittel===s.tag);assert.equal(k.kapasitet,9);assert.equal(k.sms,true);assert.equal(k.status,'kladd');console.log('Reell lagring i isolert testdatabase: kapasitet, synlighet og SMS-påminnelse.');
   await p.goto('http://lokal.lissom.no:8140/admin-ny.html#brukere');await p.getByRole('searchbox',{name:'Søk navn, brukernavn eller e-post'}).fill(s.tag);await p.getByRole('button',{name:'Endre',exact:true}).click();await p.getByRole('textbox',{name:'Navn',exact:true}).fill(s.tag+' admin endret');await p.getByRole('button',{name:'Lagre',exact:true}).click();await p.getByRole('button',{name:'Lagre bruker',exact:true}).click();await p.locator('dialog').waitFor({state:'detached'});const users=await p.evaluate(async()=>await(await fetch('/api/admin/brukere.php')).json());assert.equal(users.brukere.find(u=>u.id===s.admin).navn,s.tag+' admin endret');console.log('Brukeropplysninger lagres og leses tilbake i isolert testdatabase.');fixture('kontakt',s);await p.goto('http://lokal.lissom.no:8140/admin-ny.html#folk');await p.getByRole('searchbox',{name:'Søk navn, e-post eller telefon'}).fill(s.tag);await p.getByRole('button',{name:'Kontaktinfo',exact:true}).click();assert.equal(await p.getByRole('textbox',{name:'Medlem fra',exact:true}).inputValue(),'2026-09-01');await p.getByRole('textbox',{name:'Navn',exact:true}).fill(s.tag+' kontakt');await p.getByRole('button',{name:'Lagre',exact:true}).click();await p.locator('dialog').waitFor({state:'detached'});const contact=fixture('kontaktstatus',s);assert.equal(contact.start_dato,'2026-09-01');assert.equal(contact.slutt_dato,'2027-09-01');assert.equal(Number(contact.timer_per_mnd),11);console.log('Kontaktredigering bevarer medlemsdatoer og eget timetall.');
   await p.goto('http://lokal.lissom.no:8140/admin-ny.html#henting');await p.getByRole('searchbox',{name:'Søk kurs som er klare til henting'}).fill(s.tag);await p.getByRole('button',{name:'Åpne og publiser',exact:true}).click();await p.getByRole('button',{name:'Publiser på ferdigbrent',exact:true}).click();await p.getByRole('button',{name:'Publiser',exact:true}).click();await p.locator('dialog').waitFor({state:'detached'});const status=fixture('inspect',s);assert.ok(status.stamp);assert.equal(status.notifications.length,0);console.log('Publisering uten e-post registreres; ingen melding opprettes.');
   await p.getByRole('button',{name:'Åpne og publiser',exact:true}).click();await p.getByRole('button',{name:'Merk hentet',exact:true}).click();await p.getByRole('button',{name:'Merk ikke hentet',exact:true}).waitFor();console.log('Hentet blir lagret og lest tilbake.');
  }
  await p.goto('http://lokal.lissom.no:8140/admin-ny.html#beskjeder');await p.getByRole('button',{name:'Skriv beskjed',exact:true}).click();await p.getByRole('combobox',{name:'Mottakere',exact:true}).selectOption('okt');await p.getByRole('combobox',{name:'Kursdato',exact:true}).selectOption(String(s.session));await p.getByRole('textbox',{name:'Emne',exact:true}).fill('Testforhåndsvisning');await p.getByRole('textbox',{name:'Melding',exact:true}).fill('Kun forhåndsvisning av meldingen.');await p.getByRole('button',{name:'Forhåndsvis',exact:true}).click();await p.locator('iframe[title="E-postforhåndsvisning"]').waitFor();assert.match(await p.locator('iframe').getAttribute('srcdoc'),/Kun forhåndsvisning/);await p.getByRole('button',{name:'Send beskjed',exact:true}).click();await p.getByRole('dialog',{name:'Send beskjed?',exact:true}).getByRole('button',{name:'Avbryt',exact:true}).click();await p.locator('dialog .close').click();console.log('Faktisk e-post forhåndsvises; avbrutt utsending sender ikke.');
  if(width===1280){await p.goto(`http://lokal.lissom.no:8140/admin-ny.html#pameldte?booking=${s.booking}`);await p.getByRole('button',{name:'Rediger kursbevis',exact:true}).click();await p.getByRole('textbox',{name:'Navn på beviset',exact:true}).fill(s.tag+' bevis');await p.getByRole('checkbox',{name:'Trekk tilbake kursbeviset'}).check();await p.getByRole('button',{name:'Lagre',exact:true}).click();await p.getByRole('dialog',{name:'Kursbevis',exact:true}).waitFor({state:'detached'});const cert=await p.evaluate(async()=>await(await fetch('/api/admin/pameldte.php')).json());const row=cert.deltakere.find(r=>r.id===s.booking);assert.equal(row.bevisNavn,s.tag+' bevis');assert.equal(row.bevisSperret,true);console.log('Kursbevis lagres og leses tilbake.');}
  assert.deepEqual(errors,[]);await c.close();
 }
 const c=await browser.newContext();const p=await c.newPage();await p.goto('http://lokal.lissom.no:8140/admin-ny.html');await p.getByRole('heading',{name:'Logg inn først'}).waitFor();await c.close();console.log('Uten innlogging: ingen adminopplysninger vises.');
}finally{await browser.close();fixture('cleanup',s);}
