<?php
declare(strict_types=1);
require __DIR__ . '/nettleser/testdatabase.php';
krev_testdatabase(dirname(__DIR__));
require dirname(__DIR__) . '/app/bootstrap.php';
$s = json_decode($argv[1], true, 512, JSON_THROW_ON_ERROR);
$m = DB::en('SELECT * FROM members WHERE id=:i', ['i'=>$s['admin']]);
if (!$m || $m['navn'] !== $s['tag'] || !str_starts_with($s['tag'], 'HentingTest-')) throw new RuntimeException('Ukjent fixture');
$a = Medlemskap::avtale((int)$m['id']);
$dag = (new DateTimeImmutable('now', new DateTimeZone('Europe/Oslo')))->format('Y-m-d');
$n=0;
$sjekk = static function(bool $ok, string $tekst) use (&$n): void {if (!$ok) throw new RuntimeException($tekst);$n++;};
$sjekk(!er_aktivt_medlem($m), 'Aktiv avtale uten betaling skal ikke gi tilgang');
$p = DB::settInn('payments',['member_id'=>$m['id'],'subscription_id'=>$a['id'],'formal'=>'medlemskap','type'=>'epayment','status'=>'venter','belop_ore'=>50000,'gjelder_fra'=>$dag,'created_at'=>gmdate('Y-m-d H:i:s'),'idempotency_key'=>Vipps::uuid(),'vipps_reference'=>'TEST-'.$s['tag']]);
$sjekk(!er_aktivt_medlem($m),'Ventende betaling skal ikke gi tilgang');
DB::oppdater('payments',['status'=>'betalt'],['id'=>$p]);
$sjekk(er_aktivt_medlem($m),'Fullført betaling åpner tilgang');
$sjekk(Booking::faarMedlemsrabatt($m),'Betalt medlem har rabatt');
DB::oppdater('subscriptions',['plan'=>'Tidligere plannavn'],['id'=>$a['id']]);
$sjekk(er_aktivt_medlem($m),'Administrert planbytte skal ikke oppheve en betalt periode');
DB::oppdater('subscriptions',['plan'=>$a['plan']],['id'=>$a['id']]);
$forrige=(new DateTimeImmutable($dag))->modify('first day of previous month')->format('Y-m-d');
$forfall=Medlemskap::dekkerTil(['gjelder_fra'=>$forrige]);
DB::oppdater('payments',['gjelder_fra'=>$forrige],['id'=>$p]);
$sjekk(Medlemskap::harBetaltPeriode($m,(new DateTimeImmutable($forfall))->modify('-1 day')->format('Y-m-d')),'Dagen før forfall dekkes');
$sjekk(!Medlemskap::harBetaltPeriode($m,$forfall),'Forfallsdagen er starten på en ny ubetalt periode');
$sjekk(!Booking::faarMedlemsrabatt($m),'Ubetalt periode gir ikke rabatt');
DB::oppdater('payments',['gjelder_fra'=>(new DateTimeImmutable($dag))->modify('+1 month')->format('Y-m-d')],['id'=>$p]);
$sjekk(!er_aktivt_medlem($m),'Fremtidig betaling dekker ikke et hull nå');
DB::oppdater('payments',['gjelder_fra'=>$dag,'status'=>'refundert'],['id'=>$p]);
$sjekk(!er_aktivt_medlem($m),'Fullt refundert periode gir ikke tilgang');
DB::oppdater('payments',['status'=>'betalt','annullert_at'=>gmdate('Y-m-d H:i:s')],['id'=>$p]);
$sjekk(!er_aktivt_medlem($m),'Annullert betaling gir ikke tilgang');
$fri=$m;$fri['betaler_ikke']=1;$sjekk(er_aktivt_medlem($fri),'Eksplisitt gratismedlem beholder tilgang');
$admin=$m;$admin['rolle']='admin';$sjekk(er_aktivt_medlem($admin),'Admin beholder tilgang');
DB::kjor('DELETE FROM payments WHERE id=:i',['i'=>$p]);
echo "$n betalingsperiodekontroller bestått\n";
