<?php
declare(strict_types=1);
require __DIR__ . '/nettleser/testdatabase.php';
krev_testdatabase(dirname(__DIR__));
require dirname(__DIR__) . '/app/bootstrap.php';
$s = json_decode($argv[1], true, 512, JSON_THROW_ON_ERROR);
$m = DB::en('SELECT * FROM members WHERE id=:i', ['i'=>$s['admin']]);
if (!$m || $m['navn'] !== $s['tag'] || !str_starts_with($s['tag'], 'HentingTest-')) throw new RuntimeException('Ukjent fixture');
$a = Medlemskap::avtale((int)$m['id']);
$dag = (new DateTimeImmutable('now', new DateTimeZone('Europe/Oslo')))->format('Y-m-d');
$n=0;
$sjekk = static function(bool $ok, string $tekst) use (&$n): void {if (!$ok) throw new RuntimeException($tekst);$n++;};
$sjekk(!er_aktivt_medlem($m), 'Aktiv avtale uten betaling skal ikke gi tilgang');
$sjekk(Medlemskap::dekkerTil(['gjelder_fra'=>'2026-09-17'])==='2026-10-01','Kjøp midt i september utløper 1. oktober');
$sjekk(Medlemskap::dekkerTil(['gjelder_fra'=>'2026-01-31'])==='2026-02-01','Kjøp 31. januar hopper ikke over februar');
$sjekk(Medlemskap::dekkerTil(['created_at'=>'2026-09-30 22:30:00'])==='2026-11-01','Betalingsmåneden leses i Oslo, ikke UTC');
$p = DB::settInn('payments',['member_id'=>$m['id'],'subscription_id'=>$a['id'],'formal'=>'medlemskap','type'=>'epayment','status'=>'venter','belop_ore'=>50000,'gjelder_fra'=>$dag,'created_at'=>gmdate('Y-m-d H:i:s'),'idempotency_key'=>Vipps::uuid(),'vipps_reference'=>'TEST-'.$s['tag']]);
$sjekk(!er_aktivt_medlem($m),'Ventende betaling skal ikke gi tilgang');
DB::oppdater('payments',['status'=>'betalt'],['id'=>$p]);
$tp=DB::settInn('timepakker',['member_id'=>$m['id'],'payment_id'=>$p,'timer'=>6,'pris_ore'=>50000,'status'=>'betalt','betalt_at'=>gmdate('Y-m-d H:i:s')]);
$sjekk(!er_aktivt_medlem($m),'Ekstra timepakke er ikke betaling for medlemskapet');
$sjekk(!isset(Medlemskap::sisteBetalinger([(int)$m['id']])[(int)$m['id']]),'Ekstra timepakke vises ikke som siste medlemskapsbetaling');
DB::kjor('DELETE FROM timepakker WHERE id=:i',['i'=>$tp]);
$sjekk(er_aktivt_medlem($m),'Fullført betaling åpner tilgang');
$sjekk(Booking::faarMedlemsrabatt($m),'Betalt medlem har rabatt');
DB::oppdater('subscriptions',['plan'=>'Tidligere plannavn'],['id'=>$a['id']]);
$sjekk(er_aktivt_medlem($m),'Administrert planbytte skal ikke oppheve en betalt periode');
DB::oppdater('subscriptions',['plan'=>$a['plan']],['id'=>$a['id']]);
$forrige=(new DateTimeImmutable($dag))->modify('first day of previous month')->format('Y-m-d');
$forfall=Medlemskap::dekkerTil(['gjelder_fra'=>$forrige]);
DB::oppdater('payments',['gjelder_fra'=>$forrige],['id'=>$p]);
$sjekk(Medlemskap::harBetaltPeriode($m,(new DateTimeImmutable($forfall))->modify('-1 day')->format('Y-m-d')),'Dagen før forfall dekkes');
$sjekk(!Medlemskap::harBetaltPeriode($m,$forfall),'Forfallsdagen er starten på en ny ubetalt periode');
$midt=(new DateTimeImmutable($forrige))->modify('+16 days')->format('Y-m-d');
DB::oppdater('payments',['gjelder_fra'=>$midt],['id'=>$p]);
$sjekk(!Medlemskap::harBetaltPeriode($m,$forfall),'Resttimer fra kjøp midt i forrige måned åpner ikke ny måned');
DB::oppdater('subscriptions',['vipps_agreement_id'=>'TEST-fast-periode'],['id'=>$a['id']]);
$sjekk(Medlemskap::harBetaltPeriode($m,$forfall),'Fast trekk beholder betalt periode over månedsskiftet');
$fastForfall=Medlemskap::nesteTrekkdato($midt);
$sjekk(!Medlemskap::harBetaltPeriode($m,$fastForfall),'Fast trekk gir ikke tilgang etter betalt periodes slutt');
DB::oppdater('subscriptions',['vipps_agreement_id'=>null],['id'=>$a['id']]);
$tp=DB::settInn('timepakker',['member_id'=>$m['id'],'payment_id'=>$p,'timer'=>6,'pris_ore'=>50000,'status'=>'betalt','betalt_at'=>$midt.' 12:00:00']);
$sjekk(Timepakke::tilgodeMin((int)$m['id'])===360,'Ekstra timepakkens seks timer overføres til neste måned');
$sjekk(!er_aktivt_medlem($m),'Overførte ekstra timer åpner ikke et ubetalt månedsmedlemskap');
DB::kjor('DELETE FROM timepakker WHERE id=:i',['i'=>$tp]);
$nyMidt=(new DateTimeImmutable($forfall))->modify('+16 days')->format('Y-m-d');
DB::oppdater('payments',['gjelder_fra'=>$nyMidt],['id'=>$p]);
$sjekk(Medlemskap::harBetaltPeriode($m,$forfall),'Betalt kalendermåned åpner fra den 1., selv med eldre dato midt i måneden');
DB::oppdater('payments',['gjelder_fra'=>$forrige],['id'=>$p]);
$sjekk(!Booking::faarMedlemsrabatt($m),'Ubetalt periode gir ikke rabatt');
DB::oppdater('payments',['gjelder_fra'=>(new DateTimeImmutable($dag))->modify('+1 month')->format('Y-m-d')],['id'=>$p]);
$sjekk(!er_aktivt_medlem($m),'Fremtidig betaling dekker ikke et hull nå');
DB::oppdater('payments',['gjelder_fra'=>$dag,'status'=>'refundert'],['id'=>$p]);
$sjekk(!er_aktivt_medlem($m),'Fullt refundert periode gir ikke tilgang');
DB::oppdater('payments',['status'=>'betalt','annullert_at'=>gmdate('Y-m-d H:i:s')],['id'=>$p]);
$sjekk(!er_aktivt_medlem($m),'Annullert betaling gir ikke tilgang');
$fri=$m;$fri['betaler_ikke']=1;$sjekk(er_aktivt_medlem($fri),'Eksplisitt gratismedlem beholder tilgang');
$admin=$m;$admin['rolle']='admin';$sjekk(er_aktivt_medlem($admin),'Admin beholder tilgang');
DB::kjor('DELETE FROM payments WHERE id=:i',['i'=>$p]);
echo "$n betalingsperiodekontroller bestått\n";
