import{el,api,button,link,card,sheet,form,field,confirm,toast,list}from'./ui.js';
export function aiTools(refresh){
 const run=async body=>{if(!await confirm('Bruk AI-verktøyet?','Dette bruker den valgte AI-leverandøren og månedens kostnadstak. Resultatet kontrolleres før publisering.','Fortsett'))throw Error('Avbrutt.');return api('ai.php',body);};
 return[button('Kursboost',async()=>{try{const d=await api('kurs.php');form('Kursboost',[field('kursId','Kurs','number',{options:d.kurs.map(k=>[k.id,k.tittel])})],{},async v=>{await run({handling:'kursboost',...v});refresh();});}catch(e){toast(e.message);}}),button('Ukas forslag',async()=>{try{await run({handling:'autopilot'});refresh();}catch(e){toast(e.message);}}),button('Ny side fra søkeord',()=>form('Forslag til ny side',[field('sokeord','Søkeord','text',{required:true})],{},async v=>{await run({handling:'seoside',...v});refresh();})),button('Medlemsbrev',()=>form('Medlemsbrev',[field('om','Hva skal brevet handle om?','textarea',{required:true})],{},async v=>{await run({handling:'medlemsbrev',...v});refresh();})),button('Spør markedsassistenten',()=>form('Markedsassistent',[field('sporsmal','Spørsmål','textarea',{required:true})],{},async v=>{const r=await run({handling:'assistent',...v});sheet('Svar fra markedsassistenten',el('div',{},el('p',{text:r.svar,style:'white-space:pre-wrap'}),el('small',{text:'Kostnad: '+r.kostnad})));},{submitLabel:'Spør',successText:false})),link('AI-bilder, video og oppsett','#aibilder')];
}

export function videoTools(d,refresh){
 const upload=el('input',{type:'file',accept:'image/jpeg,image/png,image/webp','aria-label':'Last opp referansebilde'});
 upload.addEventListener('change',async()=>{if(!upload.files[0])return;upload.disabled=true;try{const body=new FormData();body.set('handling','referanse');body.set('bilde',upload.files[0]);const response=await fetch('/api/admin/gemini.php',{method:'POST',body,credentials:'same-origin'}),r=await response.json();if(!response.ok||r.ok===false)throw Error(r.feil||'Opplastingen mislyktes.');refresh();}catch(e){toast(e.message);}finally{upload.disabled=false;}});
 const generate=()=>form('Lag AI-video',[field('ledetekst','Beskriv videoen','textarea',{required:true}),field('format','Format','text',{options:[['9:16','Stående'],['16:9','Liggende']]}),field('sekunder','Lengde i sekunder','number',{options:[[4,'4 sekunder'],[6,'6 sekunder'],[8,'8 sekunder']]})],{sekunder:8},async v=>{if(!await confirm('Lag video?','Oppgitt pris: '+d.video.pris+'. Dette bruker AI-budsjettet.','Lag video'))throw Error('Avbrutt.');const r=await api('gemini.php',{handling:'videoStart',...v});sessionStorage.setItem('lissom-videojobb',r.jobb);status(r.jobb);},{submitLabel:'Lag video',successText:false});
 function status(job){const state=el('div',{},el('p',{text:'Videoen lages. Dette tar vanligvis ett til seks minutter.'}));const check=button('Kontroller om videoen er klar',async()=>{check.disabled=true;try{const r=await api('gemini.php',{handling:'videoStatus',jobb:job});if(r.ferdig){sessionStorage.removeItem('lissom-videojobb');state.replaceChildren(el('video',{src:'/'+r.url.replace(/^\//,''),controls:true,style:'max-width:100%'}),el('p',{text:'Kostnad: '+r.kostnad}),link('Last ned video','/'+r.url.replace(/^\//,'')));check.remove();}else toast('Videoen er ikke ferdig ennå.');}catch(e){toast(e.message);}finally{check.disabled=false;}});sheet('AI-video',el('div',{},state,check));}
 return[card('AI-video',el('p',{text:d.video.modell+' · '+d.video.opplosning+' · oppgitt pris '+d.video.pris}),button('Lag video',generate,'primary'),sessionStorage.getItem('lissom-videojobb')?button('Se pågående videojobb',()=>status(sessionStorage.getItem('lissom-videojobb'))):null),card('Referansebilder',el('p',{text:'De nyeste referansebildene brukes ved bildegenerering.'}),upload,list(d.referanser,r=>el('div',{class:'card'},el('img',{src:'/api/bilde.php?referanse='+encodeURIComponent(r),alt:'Referansebilde',style:'width:100%;height:180px;object-fit:cover'}),button('Fjern referanse',async()=>{if(!await confirm('Fjern referansebildet?','Bildet brukes ikke i senere genereringer.','Fjern'))return;try{await api('gemini.php',{handling:'referanseSlett',navn:r});refresh();}catch(e){toast(e.message);}}))))];
}
