import {textSuggestion} from './tekstforslag.js';
import {chooseImage} from './bilder.js';
import {el,api,button,link,badge,card,today,date,iso,shift,sheet,form,field,confirm,toast,searchable,list} from './ui.js';
const head=(name,text,actions=[])=>el('div',{class:'page-head'},el('div',{},el('p',{class:'eyebrow',text:'Lissom · Arbeidsrom'}),el('h1',{text:name}),el('p',{class:'muted',text})),el('div',{class:'actions'},actions));
const item=(name,text,actions=[])=>el('article',{class:'card list-item'},el('div',{class:'row'},el('div',{},el('strong',{text:name}),el('p',{class:'muted',text})),el('div',{class:'actions'},actions)));
export const extraRoutes=[['/admin/venteliste','venteliste'],['/admin/arskalender','arskalender'],['/admin/kursholdere','kursholdere'],['/admin/oppskrifter','verksted'],['/admin/oppskrifter?apne=vakter','vakter'],['/admin/oppskrifter?apne=brenninger','brenninger'],['/admin/oppskrifter?apne=oppskrifter','oppskrifter'],['/admin/nyttig','artikler'],['/admin/referanser','referanser'],['/admin/feilmeldinger','feilmeldinger']];
export function extraScreens(refresh){
 const mutate=async(endpoint,body,text,label='Bekreft')=>{if(!await confirm(label,text,label))return;try{const d=await api(endpoint,body);toast(d.beskjed||'Lagret.');refresh();}catch(e){toast(e.message);}};
 const save=async(endpoint,body)=>{await api(endpoint,body);refresh();};
 const workshopData=()=>api(`verkstedet.php?fra=${today()}&til=${shift(today(),90)}`);
 const fireLabels={raabrann:'Råbrann',glasurbrann:'Glasurbrann',annet:'Annet'};
 function fireEdit(r={}){form(r.id?'Endre brenning':'Ny brenning',[field('slag','Brenning','text',{options:Object.entries(fireLabels)}),field('ovn','Ovn'),field('dato','Startdato','date',{default:today(),required:true}),field('fra','Starter kl.','time',{default:'09:00',required:true}),field('sluttDato','Sluttdato','date',{default:shift(today(),1),required:true}),field('til','Ferdig kl.','time',{default:'09:00',required:true}),field('notat','Notat','textarea')],r,v=>save('verkstedet.php',{handling:'brenning',id:r.id||0,...v}));}
 async function workshop(){
 const d=await workshopData();
 const fireCard=card('Brenninger',list(d.brenninger.slice(0,4),r=>item(fireLabels[r.slag]||r.slag,r.dato+' '+r.fra+'–'+r.sluttDato+' '+r.til+' · '+r.ovn,[button('Endre',()=>fireEdit(r))]),'Ingen planlagte brenninger.'),el('div',{class:'actions'},button('Ny brenning',()=>fireEdit(),'primary'),link('Alle brenninger','#brenninger')));
 const shiftsCard=card('Vakter',list(d.vakter.slice(0,5),r=>item(r.holder||'Kursholder mangler',r.dato+' '+r.fra+'–'+r.til+' · '+r.kurs)),link('Hele vaktlista','#vakter'));
 const notesCard=card('Notater til meg selv',el('p',{text:d.notat||'Ingen notater ennå.',style:'white-space:pre-wrap'}),button('Rediger notat',()=>form('Notater til meg selv',[field('tekst','Notat','textarea')],{tekst:d.notat},v=>save('verkstedet.php',{handling:'notat',...v}))));
 const reminders=list(d.paaminnelser,r=>item(r.tekst,r.frist||'Ingen frist',[badge(r.gjort?'Gjort':'Åpen',r.gjort?'good':''),button(r.gjort?'Åpne igjen':'Merk gjort',()=>save('verkstedet.php',{handling:'paaminnelseGjort',id:r.id,gjort:r.gjort?'nei':'ja'}).catch(e=>toast(e.message))),button('Fjern',()=>mutate('verkstedet.php',{handling:'paaminnelseVekk',id:r.id},'Fjern påminnelsen fra din huskeliste.','Fjern'))]));
 const remindersCard=card('Huskeliste',reminders,button('Ny påminnelse',()=>form('Ny påminnelse',[field('tekst','Hva skal du huske?','textarea',{required:true}),field('frist','Frist','date')],{},v=>save('verkstedet.php',{handling:'paaminnelse',...v}))));
 return el('div',{},head('Verksted','Vakter, brenninger og det du skal huske.',[link('Klar til henting','#henting','primary'),link('Dugnad','#dugnad'),link('Ressurser','#ressurser')]),el('div',{class:'grid'},fireCard,shiftsCard,notesCard,remindersCard),el('div',{class:'actions',style:'margin-top:22px'},link('Oppskrifter','#oppskrifter'),link('Nyttig info','#artikler'),link('Ferie','#ferie'),link('Synlighet','#synlighet'),link('Nyttige lenker','#lenker'),link('Dokumenter','#dokumenter'),link('Vedlikehold','#verktoy')));
 }
 async function fires(){const d=await workshopData();return el('div',{},head('Brenninger','Planlegg ovnene. Brenningene vises også i kalenderen.',[button('Ny brenning',()=>fireEdit(),'primary')]),searchable(d.brenninger,r=>item(fireLabels[r.slag]||r.slag,`${r.dato} ${r.fra}–${r.sluttDato} ${r.til} · ${r.ovn}${r.notat?' · '+r.notat:''}`,[button('Endre',()=>fireEdit(r)),button('Slett',()=>mutate('verkstedet.php',{handling:'brenningVekk',id:r.id},'Ta denne brenningen ut av planen.','Slett brenning'),'danger')]),{placeholder:'Søk i brenninger'}));}
 async function shifts(){const d=await workshopData();return el('div',{},head('Vakter','Hentes fra de planlagte kursene. Kursholderen endres på kursdatoen.'),searchable(d.vakter,r=>item(r.holder||'Kursholder mangler',`${r.dato} ${r.fra}–${r.til} · ${r.kurs}`,[link('Se kurset','#kurs')]),{placeholder:'Søk kursholder eller kurs'}));}
 async function waitlist(){const d=await api('venteliste.php');const add=()=>form('Legg til på ventelista',[field('oktId','Kursdato','number',{options:d.okter.map(o=>[o.oktId,`${o.kurs||o.tittel} · ${o.naar}`])}),field('navn','Navn','text',{required:true}),field('epost','E-post','email'),field('telefon','Telefon','tel')],{},async v=>{if(!await confirm('Legg på ventelista?',`Registrer ${v.navn}. Systemet kan sende en bekreftelse.`,'Legg til'))throw Error('Avbrutt.');await save('venteliste.php',{handling:'legg-til',...v});});return el('div',{},head('Venteliste','Gi en ledig plass eller varsle personen om muligheten.',[button('Legg til person',add,'primary')]),searchable(d.venteliste,r=>item(r.navn,`${r.kurs} · ${r.naar||'Ingen bestemt dato'} · plass ${r.posisjon}`,[badge(r.status,r.status==='Venter'?'warn':''),button('Varsle om plass',()=>mutate('venteliste.php',{handling:'varsle',id:r.id},`Send ${r.navn} e-post/SMS om ledig plass. Plassen reserveres ikke automatisk.`,'Send varsel')),r.kanGiPlass?button('Gi plass',()=>form('Gi plass på kurs',[field('oktId','Velg en ledig kursdato','number',{options:r.datoer.map(o=>[o.oktId,`${o.kurs} · ${o.naar} · ${o.ledige} ledige`])})],{},async v=>{if(!await confirm('Gi kursplass?',`Sett ${r.navn} på valgt kursdato. Kontroller betaling og bekreftelse etterpå.`,'Gi plass'))throw Error('Avbrutt.');await save('venteliste.php',{handling:'gi-plass',id:r.id,...v});}),'primary'):null,button('Fjern',()=>mutate('venteliste.php',{handling:'fjern',id:r.id},`Ta ${r.navn} av ventelista.`,'Fjern'),'danger')]),{placeholder:'Søk person, kurs eller dato'}));}
 let year=Number(today().slice(0,4));const months=Array.from({length:12},(_,i)=>[i+1,new Date(2026,i,1).toLocaleDateString('nb-NO',{month:'long'})]);
 async function annual(){const d=await api(`arskalender.php?aar=${year}`);function add(mnd){form('Nytt punkt i årskalenderen',[field('tekst','Hva skjer?','textarea',{required:true})],{},v=>save('arskalender.php',{handling:'legg-til',aar:year,mnd,...v}));}return el('div',{},head('Årskalender',`${year} · Egne notater og planer, måned for måned.`,[button('← Forrige år',()=>{year--;refresh();}),button('Neste år →',()=>{year++;refresh();})]),el('div',{class:'grid three'},months.map(([mnd,name])=>card(name,list(d.punkter.filter(r=>r.mnd===mnd),r=>el('div',{class:'row'},el('p',{text:r.tekst}),el('div',{class:'actions'},button('Endre',()=>form('Endre punkt',[field('tekst','Tekst','textarea',{required:true})],r,v=>save('arskalender.php',{handling:'endre',id:r.id,...v}))),button('Flytt',()=>form('Flytt til annen måned',[field('aar','År','number',{min:2000,max:2100,required:true}),field('mnd','Måned','number',{options:months})],r,v=>save('arskalender.php',{handling:'flytt',id:r.id,...v}))),button('Slett',()=>mutate('arskalender.php',{handling:'slett',id:r.id},`Slett «${r.tekst}».`,'Slett')))),'Ingen punkter.'),button('Legg til',()=>add(mnd))))));}
 async function holders(){const d=await api('kursholdere.php');function edit(r={}){form(r.id?'Endre kursholder':'Ny kursholder',[field('navn','Navn','text',{required:true}),field('rolle','Rolle'),field('epost','E-post','email'),field('telefon','Telefon','tel'),field('kurs','Kurs'),field('signatur','Signaturbilde på kursbevis'),field('timesats','Timesats i kroner','number',{min:0}),field('betaling','Godtgjørelse','text',{options:[['lonn','Lønn'],['timer','Verkstedtimer'],['ingen','Ingen']]}),field('vises','Vis på nettsiden','checkbox')],r,async v=>{if(v.vises&&!await confirm('Vis kursholder på nettsiden?',`Publiser ${v.navn} som kursholder.`,'Publiser'))throw Error('Avbrutt.');await save('kursholdere.php',{...r,handling:'lagre',id:r.id||0,...v,vises:v.vises?'ja':'nei'});});}return el('div',{},head('Kursholdere',`Kontaktinfo og førte timer i ${d.maaned}.`,[button('Ny kursholder',()=>edit(),'primary')]),searchable(d.kursholdere,r=>item(r.navn,`${r.rolle} · ${r.timerMnd} timer denne måneden`,[r.standard?badge('Standard','good'):null,button('Endre',()=>edit(r)),button('Før timer',()=>form('Før arbeidstimer',[field('dato','Dato','date',{default:today(),required:true}),field('timer','Timer','number',{step:.25,min:.25,required:true}),field('hva','Arbeidsoppgave','text',{required:true}),field('notat','Notat','textarea')],{},v=>save('kursholdere.php',{handling:'timer',id:r.id,...v}))),!r.standard?button('Bruk som standard',()=>mutate('kursholdere.php',{handling:'standard',id:r.id},`Foreslå ${r.navn} på nye kursdatoer.`,'Velg standard')):null,button('Sett som sluttet',()=>mutate('kursholdere.php',{handling:'slett',id:r.id},`Sett ${r.navn} som sluttet. Historikken beholdes.`,'Sett som sluttet'),'danger')])),el('h2',{text:'Sist førte timer',style:'margin-top:30px'}),list(d.timer,r=>item(r.hvem,`${r.dato} · ${r.timer} timer · ${r.hva}`,[button('Slett timeføring',()=>mutate('kursholdere.php',{handling:'slettTime',timeId:r.id},'Slett denne timeføringen.','Slett'),'danger')])));}
 async function recipes(){const d=await api('verksted.php');function edit(r={}){const ingredients=(r.raavarer||[]).map(a=>`${a[0]}: ${a[1]}`).join('\n');form(r.id?'Endre oppskrift':'Ny oppskrift',[field('navn','Oppskriftsnavn','text',{required:true}),field('oppskriftType','Type','text',{options:['Glasur','Engobe']}),field('temperatur','Temperatur'),field('raavarerTekst','Råvarer og mengde','textarea',{required:true,help:'Én råvare per linje, for eksempel: Kvarts: 25'}),field('notat','Notat','textarea')],{...r,oppskriftType:r.type||'Glasur',raavarerTekst:ingredients},async v=>{const raavarer=v.raavarerTekst.split('\n').filter(s=>s.trim()).map(s=>{const pos=s.lastIndexOf(':');if(pos<1)throw Error('Skriv hver råvare som navn: mengde.');const amount=Number(s.slice(pos+1).trim().replace(',','.'));if(!(amount>0))throw Error('Hver råvare må ha en mengde over null.');return[s.slice(0,pos).trim(),amount];});await save('verksted.php',{type:'oppskrift',handling:'lagre',id:r.id||0,...v,raavarer});});}return el('div',{},head('Oppskrifter','Glasur og engobe. Oppskriftene er interne.',[button('Ny oppskrift',()=>edit(),'primary')]),searchable(d.oppskrifter,r=>item(r.navn,`${r.type} · ${r.temperatur||'Ingen temperatur'} · ${r.raavarer.length} råvarer`,[button('Se oppskrift',()=>sheet(r.navn,el('div',{},el('p',{text:r.notat||''}),list(r.raavarer,a=>el('div',{class:'row'},el('span',{text:a[0]}),el('strong',{text:a[1]})))))),button('Endre',()=>edit(r)),button('Slett',()=>mutate('verksted.php',{type:'oppskrift',handling:'slett',id:r.id},`Slett oppskriften ${r.navn}.`,'Slett'),'danger')]),{placeholder:'Søk oppskrift eller råvare'}));}
 async function articles(){const d=await api('verksted.php');function edit(r={}){form(r.id?'Endre nyttig info':'Ny artikkel',[field('tittel','Tittel','text',{required:true,wide:true}),field('dato','Dato','date'),field('status','Synlighet','text',{options:[['kladd','Utkast'],['publisert','Publisert']]}),field('ingress','Ingress','textarea'),field('innhold','Artikkeltekst','textarea'),field('bildeTekst','Bildetekst'),field('bildeAlt','Beskrivelse av bildet')],r,async v=>{if(v.status==='publisert'&&!await confirm('Publiser artikkelen?',`Publiser «${v.tittel}» som nyttig info på nettsiden.`,'Publiser'))throw Error('Avbrutt.');await save('verksted.php',{...r,type:'artikkel',handling:'lagre',id:r.id||0,...v});});}return el('div',{},head('Nyttig info','Verkstedets egne artikler og informasjon.',[button('Ny artikkel',()=>edit(),'primary')]),searchable(d.artikler,r=>item(r.tittel,r.ingress||'',[badge(r.status,r.status==='publisert'?'good':''),button('Endre',()=>edit(r)),button('Tekstforslag',()=>textSuggestion({name:r.tittel,where:'Nyttig info',fields:[['ingress','Ingress'],['innhold','Artikkeltekst','lang']],context:r,save:v=>save('verksted.php',{...r,type:'artikkel',handling:'lagre',...v})})),button('Velg bilde',()=>chooseImage(async bilde=>{if(r.status==='publisert'&&!await confirm('Oppdater artikkelbildet?','Endre bildet på den publiserte artikkelen '+r.tittel+'.','Publiser'))throw Error('Avbrutt.');await save('verksted.php',{...r,type:'artikkel',handling:'lagre',bilde});})),button('Slett',()=>mutate('verksted.php',{type:'artikkel',handling:'slett',id:r.id},`Slett artikkelen «${r.tittel}» fra nettsiden.`,'Slett'),'danger')])));}
 async function references(){const d=await api('referanser.php');function edit(r={}){form(r.id?'Endre referanse':'Ny referanse',[field('navn','Kundenavn','text',{required:true}),field('lenke','Nettadresse','url'),field('bilde','Bildeadresse'),field('logo','Logoadresse'),field('tekst','Beskrivelse','textarea'),field('sitat','Sitat','textarea'),field('sitatAv','Hvem har sagt dette?'),field('samtykke','Vi har samtykke til publisering','checkbox'),field('aktiv','Vis på nettsiden','checkbox')],r,async v=>{if(v.aktiv&&v.samtykke&&!await confirm('Publiser referansen?',`Vis ${v.navn} på nettsiden med tekst og sitat.`,'Publiser'))throw Error('Avbrutt.');await save('referanser.php',{...r,handling:'lagre',id:r.id||0,...v,aktiv:v.aktiv?'ja':'nei',samtykke:v.samtykke?'ja':'nei'});});}return el('div',{},head('Referanser','Kundehistorier vises når de er aktive og samtykke er registrert.',[button('Ny referanse',()=>edit(),'primary')]),searchable(d.kunder,r=>item(r.navn,r.tekst,[badge(r.ute?'Publisert':r.samtykke?'Skjult':'Mangler samtykke',r.ute?'good':'warn'),button('Endre',()=>edit(r)),...['bilde','logo'].map(key=>button(key==='bilde'?'Velg bilde':'Velg logo',()=>chooseImage(async url=>{if(r.ute&&!await confirm('Oppdater referansen?','Endre '+(key==='bilde'?'bildet':'logoen')+' på referansen '+r.navn+'.','Publiser'))throw Error('Avbrutt.');await save('referanser.php',{...r,handling:'lagre',[key]:url,aktiv:r.aktiv?'ja':'nei',samtykke:r.samtykke?'ja':'nei'});}))),button(r.aktiv?'Skjul':'Vis',()=>mutate('referanser.php',{handling:'veksle',id:r.id,paa:r.aktiv?'nei':'ja'},'Endre synligheten til '+r.navn+'.','Bekreft')),button('Flytt opp',()=>save('referanser.php',{handling:'flytt',id:r.id,retning:'opp'}).catch(e=>toast(e.message))),button('Flytt ned',()=>save('referanser.php',{handling:'flytt',id:r.id,retning:'ned'}).catch(e=>toast(e.message))),button('Slett',()=>mutate('referanser.php',{handling:'slett',id:r.id},`Slett referansen ${r.navn}.`,'Slett'),'danger')])));}
 async function errors(){const d=await api('feilrapporter.php');return el('div',{},head('Feilmeldinger',`${d.nye} nye meldinger. Se hva brukeren opplevde og hvilken side det gjelder.`,[button('Vis rapportknapp for brukere',()=>form('Rapportering på nettsiden',[field('til','Vis knappen til og med','date',{help:'Tomt felt skjuler knappen.'})],{til:d.apenTil},v=>save('feilrapporter.php',{handling:'bryter',...v}))),button('Lukk alle',()=>mutate('feilrapporter.php',{handling:'lukkAlle'},'Lukk alle registrerte feilrapporter.','Lukk alle'))]),searchable(d.rapporter,r=>item(r.melding||r.feiltekst||'Feilrapport',[r.navn,r.nettleser,r.side,`${r.antall} forekomster`].filter(Boolean).join(' · '),[badge(r.status,r.status==='ny'?'warn':''),button('Les detaljer',()=>sheet('Feilrapport',el('div',{},el('p',{text:r.melding}),el('pre',{text:r.feiltekst,style:'white-space:pre-wrap;overflow-wrap:anywhere'}),el('p',{text:r.side+' · '+r.skjerm}),r.bilde?el('img',{src:r.bilde,alt:'Vedlagt skjermbilde',style:'max-width:100%'}):null))),button('Merk lest',()=>save('feilrapporter.php',{handling:'status',id:r.id,status:'lest'}).catch(e=>toast(e.message))),button('Lukk',()=>mutate('feilrapporter.php',{handling:'status',id:r.id,status:'lukket'},'Lukk denne feilrapporten.','Lukk'))]),{placeholder:'Søk feiltekst, person eller side'}));}
 return{verksted:workshop,brenninger:fires,vakter:shifts,venteliste:waitlist,arskalender:annual,kursholdere:holders,oppskrifter:recipes,artikler:articles,referanser:references,feilmeldinger:errors};
}
