import{el,api,button,link,card,sheet,form,field,confirm,toast,searchable}from'./ui.js';
export async function chooseImage(save){try{const d=await api('bilder.php');const upload=el('input',{type:'file',accept:'image/jpeg,image/png,image/webp','aria-label':'Last opp eget bilde'});const error=el('p',{class:'notice error',hidden:true});const s=sheet('Velg bilde',el('div',{},el('label',{class:'field'},'Last opp et bilde',upload),error,searchable([...d.egne,...d.medfolgende],r=>el('article',{class:'card'},el('img',{src:'/'+r.mini.replace(/^\//,''),alt:r.url,loading:'lazy',style:'width:100%;height:150px;object-fit:cover;border-radius:12px'}),button('Bruk bildet',async()=>{try{await save(r.url);s.close();toast('Bildet er lagret.');}catch(e){error.textContent=e.message;error.hidden=false;}})),{placeholder:'Søk etter bilde'}),button('Fjern eget bilde',async()=>{try{await save('');s.close();toast('Bildet er fjernet.');}catch(e){error.textContent=e.message;error.hidden=false;}})));
 upload.addEventListener('change',async()=>{if(!upload.files[0])return;upload.disabled=true;try{const data=new FormData();data.set('handling','last-opp');data.set('bilde',upload.files[0]);const response=await fetch('/api/admin/bilder.php',{method:'POST',body:data,credentials:'same-origin'}),result=await response.json();if(!response.ok||result.ok===false)throw Error(result.feil||'Opplastingen mislyktes.');await save(result.url);s.close();toast('Bildet er lastet opp og valgt.');}catch(e){error.textContent=e.message;error.hidden=false;}finally{upload.disabled=false;}});
}catch(e){toast(e.message);}}

export async function imageLibrary(refresh){
 const d=await api('bilder.php');const input=el('input',{type:'file',accept:'image/jpeg,image/png,image/webp','aria-label':'Last opp bilde'});
 input.addEventListener('change',async()=>{if(!input.files[0])return;input.disabled=true;try{const body=new FormData();body.set('handling','last-opp');body.set('bilde',input.files[0]);const response=await fetch('/api/admin/bilder.php',{method:'POST',body,credentials:'same-origin'}),r=await response.json();if(!response.ok||r.ok===false)throw Error(r.feil||'Opplasting mislyktes.');toast('Bildet er lastet opp.');await refresh();}catch(e){toast(e.message);}finally{input.disabled=false;}});
 return el('div',{},el('h1',{text:'Bildebibliotek'}),el('p',{text:'Last opp bilder og velg utsnittet som vises på nettsiden.'}),card('Last opp eget bilde',input),searchable([...d.egne,...d.medfolgende],r=>card(r.navn||r.url,el('img',{src:'/'+r.mini.replace(/^\//,''),alt:r.navn||r.url,loading:'lazy',style:'width:100%;height:180px;object-fit:cover;object-position:'+(d.fokus[r.url]||'50% 50%')}),el('div',{class:'actions'},link('Åpne bildet','/'+r.url),button('Endre utsnitt',()=>{const position=(d.fokus[r.url]||'50% 50%').match(/\d+/g)||[50,50];form('Utsnitt',[field('x','Vannrett posisjon i prosent','number',{min:0,max:100,required:true}),field('y','Loddrett posisjon i prosent','number',{min:0,max:100,required:true})],{x:Number(position[0]),y:Number(position[1])},async v=>{await api('bilder.php',{handling:'fokus',fil:r.url,fokus:v.x+'% '+v.y+'%'});refresh();});}),r.egen?button('Slett bilde',async()=>{if(!await confirm('Slett bildet?','Bildet fjernes permanent. Serveren hindrer sletting av bilder som er i bruk.','Slett'))return;try{await api('bilder.php',{handling:'slett',navn:r.navn});refresh();}catch(e){toast(e.message);}},'danger'):null)),{placeholder:'Søk etter bilde'}));
}
