export const STEDER = [
  ['I dag', '#i-dag'], ['Oversikt', '/admin/oversikt'], ['Alle kurs', '/admin/kurs/alle'],
  ['Brukere', '/admin/brukere'], ['Medlemsoversikt', '/admin/medlemmer'], ['Deltakeroversikt', '/admin/deltakere'], ['Kurs og datoer', '/admin/kurs'], ['Kalender', '/admin/kalender'],
  ['Påmeldte', '/admin/pameldte'], ['Venteliste', '/admin/venteliste'], ['Klar til henting', '/admin/ferdigbrent'],
  ['Årskalender', '/admin/arskalender'], ['Kursholdere', '/admin/kursholdere'],
  ['Medlemmer', '/admin/medlemmer/alle'], ['Kursdeltakere', '/admin/deltakere/alle'], ['Medlemskap', '/admin/medlemskap'],
  ['Forespørsler', '/admin/ubesvarte'], ['Til godkjenning', '/admin/godkjenning'], ['Beskjeder', '/admin/beskjeder'],
  ['Kasse · ta betalt', '/admin/uttak'], ['Økonomi og dagsoppgjør', '/admin/okonomi'], ['Nettbutikk', '/admin/butikk'],
  ['Markedsføring', '/admin/markedsforing'], ['Innboks (SoMe)', '/admin/markedsforing?apne=innboks'], ['SEO', '/admin/seo'],
  ['Maler', '/admin/maler'], ['Varsler', '/admin/varsler'], ['Feilmeldinger', '/admin/feilmeldinger'],
  ['Skisser', '/skisser.html'], ['Det gamle admin', '/admin'],
  ['Dugnad', '/admin/ubesvarte?apne=dugnad'], ['Medlemssøknader', '/admin/medlemssoknader'],
  ['Nye påmeldinger', '/admin/nye-pameldinger'], ['Registrer medlem', '/admin/ny-registrering'],
  ['Verkstedet', '/admin/oppskrifter'], ['Vakter', '/admin/oppskrifter?apne=vakter'],
  ['Brenninger', '/admin/oppskrifter?apne=brenninger'], ['Oppskrifter', '/admin/oppskrifter?apne=oppskrifter'],
  ['Ferie', '/admin/ferie'], ['Ressurser og dreieskiver', '/admin/ressurser'],
  ['Synlighet', '/admin/oppskrifter?apne=synlighet'], ['Vedlikehold og verktøy', '/admin/oppskrifter?apne=verktoy'],
  ['Handlelister', '/admin/butikk?apne=handlelister'], ['Internbutikk', '/admin/butikk?apne=bestillmer'],
  ['Videokurs', '/admin/videokurs'], ['Kursvelger', '/admin/kursvelger'], ['Mobilvisning', '/admin/mobilvisning'],
  ['GEO', '/admin/geo'], ['Nyttig info', '/admin/nyttig'], ['Innhold', '/admin/innhold'], ['Referanser', '/admin/referanser'],
];
